##옛날과 달리 xml이 아닌 yml로 스프링 설정을 함 차이점은 중복성을 줄임 한번적으면 계속 쓸수잇음
##yml은 스프링 전체설정
server:
  port: 8000 #default값 8080
  servlet:
    context-path: / #default값 /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
   view:
     prefix: /WEB-INF/views/ #prefix 컨트롤러가 리턴을할때 앞에 붙여주는 경로명
     suffix: .jsp                         #suffix 컨트롤러가 리턴을할때 뒤에 붙여주는 경로명 중복되지않게 잘 적어야함
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cosRoot
    password: cos1234
    
  jpa:
    open-in-view: true #lazy로딩이 가능하게함 false시 영속성 컨테스트종료. 즉 lazy로딩불가
    hibernate:
      ddl-auto: update #update none 등입력가능 create는 새로만든다. 즉 처음에 create후 update로 바궈야함.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #엔티티 선언시 변수명 그대로 테이블에 있는 필드를 만들어줌
      use-new-id-generator-mappings: false #JPA가 사용하는 넘버링전략을 따라한다 안따라한다유무
    #show-sql: true #콘솔창에 sql문결과가 보이게 함
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      